version: "3.5"

services:
  redis:
    image: redis:7.0-alpine
    command: redis-server --save 20 1 --loglevel warning
    restart: always
    networks:
      - application-network
    ports:
      - "6379:6379"
    volumes:
      - cache:/data

volumes:
  cache:
    driver: local
